### ISSUE TITLE
https  ?  

### ISSUE THREAD

**Issue by jlivingstonsg** [philb61/philb61.github.io#1]
Hi.

Love your Bibviz visualization. 
I think this page is important for people to know about, 
but there us a security issue with "http".
Can you make this 
http://bibviz.com  
to a "https" on your server?
Can you then make the 
https://bibviz.com  
link to 
https://philb61.github.io/

Regards  MagI
3D Tetris wizard :)
https://blockout.nu

**Comment by philb61** [comment]
I don't control the domain.  This is really an issue for the original [bibviz repo](https://github.com/bibviz/bibviz).

This was just put up quickly so that bibviz could be back up, but the domain hijacking has been resolved.

**Comment by jlivingstonsg** [comment]
:)
